@startuml
'https://plantuml.com/class-diagram

class MoneyDiceGame {
}

class Die {
    faceValue
}

class Player {
    name

}
class Fields{
    number
    name
    money
    extra turn
}

class Account{
 money
}

MoneyDiceGame "1" -r "2" Player : Includes
MoneyDiceGame "1" -l "2" Die : Includes
MoneyDiceGame "1" -- "12" Fields : Includes
Player  "1" -d- "1" Account: Includes
@enduml