@startuml
'https://plantuml.com/sequence-diagram

actor Player
Player -[hidden]-> GUI
GUI -[hidden]-> MoneyDiceGame

MoneyDiceGame -> MoneyDiceGame : main()

GUI <- MoneyDiceGame : initializeGUI()
GUI --> MoneyDiceGame : gui3
Player -> GUI : interacts

loop for each player (2x)
    GUI <- MoneyDiceGame : askPlayerName()
    GUI --> MoneyDiceGame : playerName
    MoneyDiceGame -> MoneyDiceGame : createPlayer(playerName)
end

loop players want to keep playing
    GUI <- MoneyDiceGame : newGame()
    loop no player won
        loop for each player (2x)
            GUI <- MoneyDiceGame : askRollDice()
            GUI -> MoneyDiceGame : rollDice()
            GUI <-- MoneyDiceGame : diceValues, playerWon
            GUI -> GUI : updateDice(diceValues)
        end
    end
    GUI <- MoneyDiceGame : askPlayAgain()
    GUI --> MoneyDiceGame : playersWantToKeepPlaying
end

@enduml